/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurgicalExportsRouteImport } from './routes/surgical-exports'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MedicineExportsRouteImport } from './routes/medicine-exports'
import { Route as MedicalExportsRouteImport } from './routes/medical-exports'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SurgicalExportsRoute = SurgicalExportsRouteImport.update({
  id: '/surgical-exports',
  path: '/surgical-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineExportsRoute = MedicineExportsRouteImport.update({
  id: '/medicine-exports',
  path: '/medicine-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExportsRoute = MedicalExportsRouteImport.update({
  id: '/medical-exports',
  path: '/medical-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/services': typeof ServicesRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/services': typeof ServicesRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/services': typeof ServicesRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/medical-exports'
    | '/medicine-exports'
    | '/services'
    | '/surgical-exports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/medical-exports'
    | '/medicine-exports'
    | '/services'
    | '/surgical-exports'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/medical-exports'
    | '/medicine-exports'
    | '/services'
    | '/surgical-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MedicalExportsRoute: typeof MedicalExportsRoute
  MedicineExportsRoute: typeof MedicineExportsRoute
  ServicesRoute: typeof ServicesRoute
  SurgicalExportsRoute: typeof SurgicalExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surgical-exports': {
      id: '/surgical-exports'
      path: '/surgical-exports'
      fullPath: '/surgical-exports'
      preLoaderRoute: typeof SurgicalExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-exports': {
      id: '/medicine-exports'
      path: '/medicine-exports'
      fullPath: '/medicine-exports'
      preLoaderRoute: typeof MedicineExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exports': {
      id: '/medical-exports'
      path: '/medical-exports'
      fullPath: '/medical-exports'
      preLoaderRoute: typeof MedicalExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MedicalExportsRoute: MedicalExportsRoute,
  MedicineExportsRoute: MedicineExportsRoute,
  ServicesRoute: ServicesRoute,
  SurgicalExportsRoute: SurgicalExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
