/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurgicalExportsRouteImport } from './routes/surgical-exports'
import { Route as MedicineExportsRouteImport } from './routes/medicine-exports'
import { Route as MedicalExportsRouteImport } from './routes/medical-exports'
import { Route as IndexRouteImport } from './routes/index'

const SurgicalExportsRoute = SurgicalExportsRouteImport.update({
  id: '/surgical-exports',
  path: '/surgical-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineExportsRoute = MedicineExportsRouteImport.update({
  id: '/medicine-exports',
  path: '/medicine-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalExportsRoute = MedicalExportsRouteImport.update({
  id: '/medical-exports',
  path: '/medical-exports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/medical-exports': typeof MedicalExportsRoute
  '/medicine-exports': typeof MedicineExportsRoute
  '/surgical-exports': typeof SurgicalExportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/medical-exports'
    | '/medicine-exports'
    | '/surgical-exports'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/medical-exports' | '/medicine-exports' | '/surgical-exports'
  id:
    | '__root__'
    | '/'
    | '/medical-exports'
    | '/medicine-exports'
    | '/surgical-exports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MedicalExportsRoute: typeof MedicalExportsRoute
  MedicineExportsRoute: typeof MedicineExportsRoute
  SurgicalExportsRoute: typeof SurgicalExportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surgical-exports': {
      id: '/surgical-exports'
      path: '/surgical-exports'
      fullPath: '/surgical-exports'
      preLoaderRoute: typeof SurgicalExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-exports': {
      id: '/medicine-exports'
      path: '/medicine-exports'
      fullPath: '/medicine-exports'
      preLoaderRoute: typeof MedicineExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-exports': {
      id: '/medical-exports'
      path: '/medical-exports'
      fullPath: '/medical-exports'
      preLoaderRoute: typeof MedicalExportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MedicalExportsRoute: MedicalExportsRoute,
  MedicineExportsRoute: MedicineExportsRoute,
  SurgicalExportsRoute: SurgicalExportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
